require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - frontend/node_modules/**/*
    - frontend/tmp/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - tmp/**/*
    - db/Schemafile
  SuggestExtensions: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantRegexpArgument:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/SymbolArray:
  Enabled: false

# 引数のケツカンマ強制
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# Arrayのケツカンマ強制
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Hashのケツカンマ強制
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# https://github.com/team-youtrust/youtrust-webapp/pull/1219#discussion_r521856706
Style/SafeNavigation:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/ParameterLists:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

# 1行で書くべきif/unless文かどうかは書き手に委ねる
Style/IfUnlessModifier:
  Enabled: false

# "#{hoge}" でも hoge.to_s でもOK
Style/RedundantInterpolation:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/PredicateMatcher:
  Strict: true
  EnforcedStyle: explicit
  AllowedExplicitMatchers:
    - have_http_status

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/models/notification/**/*.rb'
    - 'lib/**/*.rb'
    - 'app/lib/**/*.rb'

Naming/BlockForwarding:
  Enabled: false
